[package]
name = "nn_n"
version = "0.1.0"
edition = "2024"
authors = ["Davis Wolfermann"]

[dependencies]
rand = "0.9.0"
rand_distr = "0.5.1"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
plotters = "0.3.7"
ndarray-npy = "0.9.1"