name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

  build-and-test:
    runs-on: ubuntu-latest
    needs:
      - prepare

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose --all-targets --all-features
      - name: Run Tests
        run: cargo test --verbose --all-targets --all-features

  clippy:
    runs-on: ubuntu-latest
    needs:
      - prepare

    steps:
      - uses: actions/checkout@v4
      - name: Check clippy
        run: cargo clippy --all-targets --all-features -- -D warnings